[package]
name = "todoapps"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
askama = "0.12"
askama_actix = "0.14"
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio"] }
